[package]
name = "cgt"
version = "0.2.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"
homepage = "https://cgt.t4ccer.com/"
documentation = "https://docs.rs/cgt"
exclude = ["papers"]
keywords = ["cgt", "combinatorial-game-theory"]
categories = ["mathematics", "science"]

[dependencies]
gcd = "2.3.0"
itertools = "0.10.5"
num-rational = { version = "0.4.1", default-features = false, features = ["std"]}
nom = "7.1.3"
num = "0.4.0"
num-derive = "0.4.0"
num-traits = "0.2.15"
serde_repr = { version = "0.1.12", optional = true}
# Later versions introduce binary blob: https://github.com/serde-rs/serde/issues/2538
serde = { version = "<=1.0.171", optional = true}
elsa = "1.8.1"
auto_ops = "0.3.0"

[features]
serde = ["dep:serde", "dep:serde_repr", "num-rational/serde"]
statistics = []
pedantic = []

[workspace]
members = ["cgt-cli", "cgt-website"]

[profile.release]
lto = true
panic = "abort"
