[package]
name = "cg"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgrs"

[dependencies]
bit-vec = "0.6.3"
lazy_static = "1.4.0"
nom = "7.1.3"
