[package]
name = "cgt"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"

[dependencies]
gcd = "2.3.0"
itertools = "0.10.5"
num-rational = { version = "0.4.1", default-features = false, features = ["std"]}
serde = { version = "1.0.163", features = ["std", "derive"], optional = true}
bincode = { version = "1.3.3", optional = true}
elsa = { git = "https://github.com/t4ccer/elsa", branch = "t4/sync-serde" }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:bincode", "num-rational/serde", "elsa/serde"]

[workspace]
members = ["cgt-cli"]
