[package]
name = "cgt"
version = "0.3.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"
homepage = "https://cgt.t4ccer.com/"
documentation = "https://docs.rs/cgt"
exclude = ["papers"]
keywords = ["cgt"]
categories = ["mathematics", "science"]

[dependencies]
ahash = "0.8.3"
append-only-vec = "0.1.3"
auto_ops = "0.3.0"
itertools = "0.10.5"
nom = "7.1.3"
num-rational = { version = "0.4.1", default-features = false, features = ["std"]}
# Later versions introduce binary blob: https://github.com/serde-rs/serde/issues/2538
serde = { version = "<=1.0.171", optional = true}
serde_repr = { version = "0.1.12", optional = true}

[dev-dependencies]
quickcheck = { version = "1.0", default-features = false }

[features]
serde = ["dep:serde", "dep:serde_repr", "num-rational/serde"]
pedantic = []

[workspace]
members = ["cgt-cli", "cgt-py"]

[profile.release]
lto = true
panic = "abort"
