[package]
name = "cgt"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"

[dependencies]
serde = { version = "1.0.163", features = ["std", "derive"], optional = true}

[features]
serde = ["dep:serde"]

[workspace]
members = ["cgt-cli"]