[package]
name = "cgt"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"

[dependencies]
gcd = "2.3.0"
itertools = "0.10.5"
num-rational = { version = "0.4.1", default-features = false, features = ["std"]}
elsa = { git = "https://github.com/t4ccer/elsa", branch = "t4/sync-serde" }
nom = "7.1.3"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
concurrent_lru = "0.2.0"
serde_repr = { version = "0.1.12", optional = true}
serde = { version = "1.0.164", optional = true}

[features]
serde = ["dep:serde", "dep:serde_repr"]
statistics = []
pedantic = []

[workspace]
members = ["cgt-cli", "cgt-website", "cgt-py-adapter"]
