[package]
name = "cgt"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/cgt-rs"
description = "Library to work with Combinatorial Games"

[dependencies]
bit-vec = "0.6.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
queues = "1.1.0"