[package]
name = "cgt_gui"
version = "0.5.1"
edition = "2021"

[dependencies]
raylib = { version = "5.0.2" }
cgt = { path = "../.", version = "0.5.1" }

[features]
default = ["wayland"]
wayland = ["raylib/wayland"]

[[bin]]
name = "cgt-gui"
path = "src/main.rs"